# Changes here will be overwritten by Copier
_commit: 2.0.0
_src_path: gh:markusritschel/cookiecutter-pyproject
command_line_interface: Click
docs_engine: Sphinx
github_user: markusritschel
is_research_project: false
package_name: my_code_base
project_description: This is a collection of routines that I've developed over time
    and that I use in my daily work.
project_license: MIT license
project_name: My Code Base
project_slug: my-code-base
project_version: 0.1.0
user_email: git@markusritschel.de
user_name: Markus Ritschel

