name: my_code_base
channels:
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - mamba
  - jupyterlab
  - ipywidgets
  - nb_conda_kernels
  - ipykernel
  - jupytext
  - jupyternotify
  - seaborn
  - nodejs
  - tqdm
  - pip
  - matplotlib
  - numpy
  - pandas
  - xarray
  - markdown
  - python-dotenv
  - docopt
  - click
  - pytest
  - cartopy
  - ca-certificates
  - certifi
  - openssl
  - xarrayutils
  - sphinx
  - nbsphinx
  - sphinx-issues
  - sphinxcontrib-napoleon
  - sphinx-book-theme
  - pydata-sphinx-theme
  - sphinx_rtd_theme
  - myst-parser
  - sphinxcontrib-bibtex
  - sphinxcontrib-apidoc
  - multipledispatch
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocstrings-python
  - markdown-it-py
  - traitlets
  - shapely
  - importlib_metadata
  - tzdata
  - backports
  - jsonschema
  - jpeg
  - nbclient
  - attrs
  - libgomp
  - jupyterlab_server
  - liblapack
  - pyyaml
  - toolz
  - libogg
  - libffi
  - libev
  - libsodium
  - libzlib
  - nbclassic
  - scipy
  - cffi
  - pickleshare
  - argon2-cffi-bindings
  - packaging
  - json5
  - griffe
  - libgfortran5
  - pandoc
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-jsmath
  - mergedeep
  - libpq
  - fsspec
  - openjpeg
  - mysql-common
  - reproc
  - zeromq
  - pyqtchart
  - pymdown-extensions
  - regex
  - astunparse
  - krb5
  - patsy
  - dbus
  - conda-package-handling
  - mistune
  - jupyterlab_pygments
  - prometheus_client
  - pyzmq
  - ld_impl_linux-64
  - pytz
  - accessible-pygments
  - sphinxcontrib-htmlhelp
  - defusedxml
  - cryptography
  - nest-asyncio
  - lerc
  - nbconvert-core
  - gettext
  - locket
  - colorama
  - beautifulsoup4
  - pathspec
  - jinja2
  - dask
  - pbr
  - jupyter
  - libedit
  - jupyter_core
  - anyio
  - proj
  - six
  - charset-normalizer
  - gstreamer
  - libuuid
  - yaml
  - pyerfa
  - entrypoints
  - argon2-cffi
  - conda
  - qt
  - libwebp-base
  - notebook-shim
  - ipython
  - libgfortran-ng
  - ipython_genutils
  - sphinxcontrib-qthelp
  - libiconv
  - backports.functools_lru_cache
  - imagesize
  - xorg-libxdmcp
  - xorg-libxau
  - libmamba
  - libgcc-ng
  - dask-core
  - qtpy
  - libxkbcommon
  - partd
  - brotli-bin
  - expat
  - pluggy
  - bzip2
  - zstd
  - executing
  - prompt_toolkit
  - watchdog
  - urllib3
  - keyutils
  - pybtex
  - c-ares
  - libssh2
  - libpng
  - readline
  - jupyter_client
  - jedi
  - webencodings
  - latexcodec
  - cycler
  - libglib
  - ncurses
  - libstdcxx-ng
  - pycosat
  - pybind11-abi
  - flit-core
  - exceptiongroup
  - pyopenssl
  - nspr
  - libopus
  - libbrotlidec
  - python-dateutil
  - fmt
  - qtconsole-base
  - matplotlib-base
  - iniconfig
  - icu
  - decorator
  - libsqlite
  - debugpy
  - pockets
  - websocket-client
  - pexpect
  - asttokens
  - notebook
  - pysocks
  - lz4-c
  - sqlite
  - pycparser
  - brotli
  - sphinxcontrib-devhelp
  - yaml-cpp
  - font-ttf-dejavu-sans-mono
  - markupsafe
  - importlib_resources
  - distributed
  - tornado
  - nbformat
  - jupyter_server
  - pyqt
  - alabaster
  - snowballstemmer
  - pygments
  - libclang
  - astropy
  - mkdocs-autorefs
  - jupyterlab_widgets
  - fonts-conda-forge
  - idna
  - geos
  - python_abi
  - parso
  - zict
  - terminado
  - mkdocs-material-extensions
  - stack_data
  - pyshp
  - _libgcc_mutex
  - mysql-libs
  - pyqt5-sip
  - babel
  - nss
  - fontconfig
  - pillow
  - libtiff
  - importlib-metadata
  - ghp-import
  - alsa-lib
  - fonttools
  - pyyaml-env-tag
  - pybtex-docutils
  - cloudpickle
  - lzo
  - brotlipy
  - setuptools
  - pyrsistent
  - pkgutil-resolve-name
  - font-ttf-ubuntu
  - lz4
  - libarchive
  - ptyprocess
  - libcblas
  - bokeh
  - gst-plugins-base
  - sniffio
  - libxml2
  - tomli
  - freetype
  - font-ttf-inconsolata
  - pcre2
  - pthread-stubs
  - libopenblas
  - libsolv
  - reproc-cpp
  - widgetsnbextension
  - libbrotlicommon
  - libevent
  - pure_eval
  - libuv
  - dataclasses
  - nbconvert
  - sphinxcontrib-applehelp
  - mdurl
  - libbrotlienc
  - libxcb
  - glib
  - sortedcontainers
  - nbconvert-pandoc
  - send2trash
  - tk
  - platformdirs
  - libcurl
  - xz
  - backcall
  - libmambapy
  - libllvm13
  - typing_extensions
  - typing-extensions
  - zipp
  - bleach
  - libnghttp2
  - tblib
  - seaborn-base
  - wcwidth
  - font-ttf-source-code-pro
  - zlib
  - pyproj
  - cytoolz
  - fonts-conda-ecosystem
  - libdeflate
  - statsmodels
  - contourpy
  - soupsieve
  - psutil
  - pandocfilters
  - pyparsing
  - jupyter_console
  - docutils
  - msgpack-python
  - libnsl
  - pyqtwebengine
  - glib-tools
  - lcms2
  - qtconsole
  - requests
  - matplotlib-inline
  - python-fastjsonschema
  - munkres
  - unicodedata2
  - tinycss2
  - kiwisolver
  - libvorbis
  - python
  - ruamel_yaml
  - wheel
  - _openmp_mutex
  - prompt-toolkit
  - pyqt-impl
  - libblas
  - lxml
  - sphinx-autoapi
  - pip:
      - attrs
      - cattrs
      - docutils
      - esbonio
      - jinja2
      - lsprotocol
      - mpl-axes-aligner
      - pygls
      - pyspellchecker
      - tabulate
